apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
    - wget
    - -O
    - /csi/index.html
    - http://info.cern.ch
    volumeMounts:
    - name: csi
      mountPath: /csi
  volumes:
    - name: csi
      persistentVolumeClaim:
        claimName: csi-pvc
