apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-clusterrole
rules:
- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["create", "watch", "delete", "list", "patch"]
- apiGroups: [""]
  resources: ["events", "persistentvolumes", "persistentvolumeclaims", "services"]
  verbs: ["create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments/status", "deployments"]
  verbs: ["create", "delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: mysql-sa
  namespace: homework
roleRef:
  kind: ClusterRole
  name: mysql-clusterrole
  apiGroup: rbac.authorization.k8s.io
