apiVersion: v1
kind: Pod
metadata:
  name: distroless-container-pod
  namespace: default
spec:
  containers:
  - name: nginx-distroless
    image: kyos0109/nginx-distroless
    ports:
    - containerPort: 80
